name: Пример непрерывной интеграции
on: [push]
jobs:
<<<<<<< HEAD
  testing:
=======
  test-build:
>>>>>>> 26c8a9cd207eb7db0a20ffbeb752becaf4a6709e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install django

      - name: Testing
        run: python manage.py test
<<<<<<< HEAD

  build-deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: imsiw0990/students:latest
=======
>>>>>>> 26c8a9cd207eb7db0a20ffbeb752becaf4a6709e
